
name: babe
version: '0.5 beta'
summary: Tiny music player
description: |
  Babe will handle your whole music collection, letting you create custom playlists to organize your music. You can also filter your music by artist, title, album, genre, date and location. Babe let's you babe-mark your favorite YouTube music videos into your local collection by using the Chromium extension. Think of Babe as the playlist where all your favorite tracks at the moment are. And when needed you also have an integrated collection manager..

grade: devel
confinement: devmode

apps:
  babe:
    command: desktop-launch Babe

parts:
  babe:
    plugin: qmake
    qt-version: qt5
    source: https://github.com/milohr/babe-qt.git
    after: [desktop-qt5]
